kind: pipeline
name: default

steps:
- name: sls-install
  image: node:8.10
  commands:
    - npm install

- name: sls-lint
  image: node:8.10
  group: ci
  commands:
    - npm run lint

- name: sls-test
  image: node:8.10
  group: ci
  commands:
    - npm test -- --ci --coverage

- name: sls-coverage
  image: plugins/codecov
  group: ci
  settings:
    token:
      from_secret: CODECOV_TOKEN
    files:
     - '*.xml'
    paths:
      - .output/reports/coverage

- name: publish
  image: node:8.10
  group: cd
  when:
    branch:
      - master
    event:
      - push
    status:
      - success
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
    - npm run release
