service: serverless-aws-node-starter

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:STAGE, 'dev'}
  region: ${opt:AWS_REGION, 'eu-west-1'}

plugins:
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
